README.md

Added TaoHe, a library written in Move.

Added TaoHe: collection of nestable Move resources

---

README.md

Updating Starcoin discord invitation link (based on information
from @jolestar in #6).

Updated outdated Starcoin discord invitation

---

README.md

Following major Awesome style guidelines and committing early, so the next list additions could adhere to the Awesome style guidelines from this point onwards.
This commit is mostly about formatting, and the content itself is mostly intact at this point.
The next PR will contain content changes (mostly additions, like descriptions, etc.).
Part of https://github.com/MystenLabs/awesome-move/issues/9.

Making the list (mostly) Awesome-compatible

---

CONTRIBUTING.md

Copied widely accepted guidelines from
https://github.com/sindresorhus/awesome-nodejs/blob/main/contributing.md.
Dropped the strictest requirements, ending up with a list of
reasonable guidelines, while still being awesome compliant.
Part of #9.

Amended contribution guidelines

---

README.md

Recent changes now passing `npx awesome-lint`.

Linting fixes

---

README.md

Adds this vimscript I wrote for syntax and indentation support with vim / neovim.

Update readme to include move.vim

---

README.md

- Gave a better link rather than the link to the example folder.

Updated the link for the Move-on-EVM project

---

README.md

- Add pentagonxyz/movemate to Libraries list
- Also fixed a typo in the ACL.move listing

Add pentagonxyz/movemate to Libraries list

---

README.md

Correcting some brand names, and general style fixes.

Nitpicks: brands and style

---

README.md

Added Move Patterns and Chinese translations for both of the move books.

Updated books

---

README.md

1, Add the first Cross-Chain Bridge between Move and EVM.
2, Add more tokens on Starcoin.
3, Add more wallets on Sui and Aptos.
4, Add Starcoin IDE maintained by the Starcoin team.
5, Add the tutorials of Move and SmartContract Development.

Add the first Cross-Chain Bridge between Move and EVM.

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Added a PR template outlining the most important requirements for an addition. Also added a requirement for the commit message format.
Also replaced "guidelines" with "requirements" since the list has been recently gaining traction.

Added PR template & amended CONTRIBUTING.md

---

README.md

Now passing lint. Also changed the title to Title Case.

Added ToC entry for the Blog Posts category

---

README.md

Library for parsing cron expression written in Move language

Add Move cron parser library

---

README.md

Add SDKs （Table of contents）

---

README.md

Add Move Community (MoveChina)--- The largest Move language Chinese community.

---

README.md

Update 0L discord to slugs instead of invitation codes

Update 0L discord to slugs instead of invitation codes.

---

README.md

Add a project: Support Move VM for layer2 of BTC.

---

README.md

feat: add OriginByte NFT protocol

Add OriginByte NFT protocol

---

README.md

Add chrome extension store url for Suiet Wallet

feat: add Suiet extension store url

---

README.md

Add a defi: Aptos AMM swap.

---

README.md

Update Sui wallet and Sui wallet adapter links

---

README.md

add security section

---

docs/problem_statement.md

Update problem statement

---

README.md

Add Aptos OmniSwap.

---

README.md

[Move Language](https://imcoding.online/courses/move-language) is an interactive Move course maintained by [imcoding.online](https://imcoding.online). It's unique in that you can write and run code directly in the browser while learning.

Add interactive Move course

---

README.md

AMM Swap SDK on Sui Network.

---

README.md

Dola Protocol is a Decentralized Omnichain Liquidity Aggregation Protocol with the single coin pool of each public chain as the core, Wormhole, Layerzero and other cross-chain messaging protocols as the bridge, and Sui public chain as the settlement center.

Add DolaProtocol

---

README.md

Add MoveDID

---

README.md

Adding a few links to the move-focused Ethos projects.

Add Ethos Wallet and Ethos Connect

---

README.md

Not sure if there's another category that makes more sense. It includes a library with some generally useful functions and data structures, but it's not primarily designed as one.

Add aoc-move

---

README.md

Fixed linting errors regarding some recent additions.

Fixed linting errors

---

README.md

Add Sui SDKs for other languages

---

README.md

Hello, adding Sui Move by Example to the book list for the Sui Move variant.

Adding Sui Move by Example

---

README.md

go-sui-indexer is an off-fullnode service to serve data from Sui Node.

go-sui-indexer is an off-fullnode service to serve data from Sui Node.
